  - vm_name: "{{ range_id }}-GOAD-DC04"
    hostname: "{{ range_id }}-DC04"
    template: win2025-server-x64-tpm-template
    vlan: 10
    ip_last_octet: 13
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    roles:
      - ludus_enable_mdi_gpo
