# add windows server 2025 box
boxes.append(
  { :name => "{{lab_name}}-DC04",
    :ip => "{{ip_range}}.13",
    :box => "StefanScherer/windows_2025",
    :os => "windows",
    :cpus => 2,
    :mem => 3000
  }
)
